events{
    worker_connections 1024;
}

# stream {
#     upstream file_sync_backend {
#         server 127.0.0.1:9000 down;
#     }
#
#
# }TODO:Needed only in TCP transport layer,implement later
http{
    map $http_upgrade $connection_upgrade{#$http_upgrade represents Upgrade field value in the client HTTP requeset header,$connection_upgrade is a customed new varieble whose value is determined by the rule in parentheses.
        default upgrade;#if #http_upgrade isn't '',$connection_upgrade's value is upgrade
        ''      close;#If $http_upgrade is ''(is null),$connection_upgrade's value is close
    }
    server{
        listen 80;
        server_name localhost;
        location /ws/{

            
        }
    }
}
