//
// Created by bysunlits on 2026/9/6.
//
#include <stdio.h>

enum INFOMESSAGE
{
	START_MSG, IN_PROGRESS_MSG, END_MSG
};

int main()
{
	{
		size_t buffer[256*1024];
		if (fread(buffer,1,sizeof(buffer),stdin)) {
			//Firstly,read the bytes to buffer
			//1.1,recognise which client sent it,every client should register itself by the api /regiser,then allocate a uuid to the client
			//1.2 if it is start snippet,It should be allocated with a int by the client itself,Alone with this,a uuid also was send over,it's the uuid server allocate to it to recognise it before,the int will be linked to the client's uuid to recognise whose the snippet is.
			//1.3 read the config file to get where the snippet should be sent to,the file should be generated by the user configuration in server,if nothing there,the snippet will be spread to everywhere
			//secondly,check the hash to verify the integrity of the snippet
			//2.1,if the file has broken,inform client to resend the file
			//2.2 if that snippet is integral,send it right now
			//2.4,find the client the snippet want to send,
			//Thirdly,send the file to other client again,
		}
	}

}
